---
- name: Ensure media app folder exists
  file:
    mode: "0755"
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ media_apps.base_path }}"
    - "{{ media_apps.base_path }}/config"

- name: Template docker-compose
  template:
    src: templates/docker-compose.yml.j2
    dest: "{{ media_apps.base_path }}/docker-compose.yml"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: "0644"

# https://jellyfin.org/docs/general/administration/hardware-acceleration.html#raspberry-pi-3-and-4
- name: Update GPU allocated memory
  become: true
  ansible.builtin.lineinfile:
    path: /boot/config.txt
    regexp: '^gpu_mem.*'
    line: gpu_mem=320
    owner: root
    group: root
    mode: "0755"

- name: Setup nginx hosts
  include_tasks: nginx.yml
  loop: "{{ media_apps.apps }}"

# https://jellyfin.org/docs/general/administration/hardware-acceleration.html#raspberry-pi-3-and-4
- name: Add current user to video group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/bash
    groups: video
    append: yes

- name: Add domains to certificate to be generated
  set_fact:
    # Thanks https://stackoverflow.com/a/49748012/6187576
    certbot_certs: '{{ certbot_certs + [ { "domains": media_apps.apps | map(attribute="domain") | list } ] }}'
