---
- name: Dell workstation setup
  hosts: dell
  gather_facts: true

  roles:
    - role: sourcejedi.rpmfusion_free
      become: true
      tags: [rpm]
    - role: fedora_dependencies
      become: true
      tags: [fedora_dependencies]
    - role: mise
      tags: [mise]
    - role: hostname
      become: true
      tags: [hostname]
    - role: jaredhocutt.gnome_extensions
      tags: [gnome_extensions]
    - role: ssh_config
      tags: [ssh_config]
    - role: git_config
      tags: [git_config]
    - role: kdrive
      tags: [kdrive]
    - role: jetbrains_toolbox
      tags: [jetbrains_toolbox]
    - role: gnome
      tags: [gnome]
    - role: commons
      tags: [commons]
