---
- name: GOP workstation setup
  hosts: gop
  gather_facts: true

  pre_tasks:
    - name: "Include vaulted locals variables"
      ansible.builtin.include_vars:
        file: "playbooks/gop/locals.yml"
      tags: always

  roles:
    - role: fedora_dependencies
      become: true
      tags: [fedora_dependencies]
    - role: mise
      tags: [mise]
    - role: sourcejedi.rpmfusion_free
      become: true
      tags: [rpm]
    - role: jaredhocutt.gnome_extensions
      tags: [gnome_extensions]
    - role: ssh_config
      tags: [ssh_config]
    - role: git_config
      tags: [git_config]
    - role: kdrive
      tags: [kdrive]
    - role: jetbrains_toolbox
      tags: [jetbrains_toolbox]
    - role: gnome
      tags: [gnome]
    - role: commons
      tags: [commons]
    - role: gop
      tags: [gop]
    - role: git_credential_keepassxc
      tags: [git_credential_keepassxc]
