---
# ASDF
asdf_plugins:
  # - name: docker-compose
  #   repository: "https://github.com/virtualstaticvoid/asdf-docker-compose.git"
  #   versions:
  #     - 1.29.2
  #   global: 1.29.2
  #   yum_deps: []
  - name: "rust"
    repository: "https://github.com/asdf-community/asdf-rust.git"
    versions:
      - "1.62.0"
    global: "1.62.0"
    yum_deps: []
  - name: "terraform"
    versions:
      - "1.2.1"
      - "1.2.5"
    global: "1.2.5"
    yum_deps: []
  - name: "direnv"
    versions: ["2.31.0"]
    global: "2.31.0"
    yum_deps: []
  - name: "fzf"
    versions: ["0.30.0"]
    global: "0.30.0"
    yum_deps: []
  - name: "starship"
    versions: ["0.58.0"]
    global: "0.58.0"
    yum_deps: []

asdf_version: "v0.10.2"
asdf_legacy_version_file: "no"

# HOSTNAME
hostname_name: dell
hostname_fqdn: dell.localhost

# GNOMES EXTENSIONS
gnome_extension_ids:
  # https://extensions.gnome.org/extension/1162/emoji-selector/
  - 1162
  # https://extensions.gnome.org/extension/615/appindicator-support/
  - 615
  # https://extensions.gnome.org/extension/600/launch-new-instance/
  - 600
  # https://extensions.gnome.org/extension/1262/bing-wallpaper-changer/
  - 1262
  # https://extensions.gnome.org/extension/7/removable-drive-menu/
  - 7
  # https://extensions.gnome.org/extension/1112/screenshot-tool/
  - 1112
  # https://extensions.gnome.org/extension/906/sound-output-device-chooser/
  - 906
  # - 1503  # https://extensions.gnome.org/extension/1503/tray-icons/
  # https://extensions.gnome.org/extension/4679/burn-my-windows/
  - 4679

# DOCKER
docker_install_compose: false
docker_users: ["{{ ansible_user_id }}"]
