- name: Download rpmfusion release RPM
  get_url:
    url: "https://download1.rpmfusion.org/{{ repo }}/fedora/rpmfusion-{{ repo }}-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    dest: /ansible-managed/rpmfusion/

- name: Verify rpmfusion release RPM
  command: rpm --checksig rpmfusion-{{ repo }}-release-{{ ansible_distribution_major_version }}.noarch.rpm
  args:
    chdir: /ansible-managed/rpmfusion/
  changed_when: False
  check_mode: False

- name: Install rpmfusion release RPM
  package:
    name: /ansible-managed/rpmfusion/rpmfusion-{{ repo }}-release-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present
  register: install

# This test may be slow, only bother when changed.
# (In which case, the next use of dnf would probably have had to do this anyway).
# Do not defer this, as other roles may add more drop-in configs.
- name: Test "dnf check-update"
  when: install.changed
  command: |
    dnf \
        --disablerepo="*" --enablerepo=rpmfusion-{{ repo }} \
        check-update
  register: dnf_check_update
  # exit status is 0 on success, 100 if updates available (otherwise 100)
  failed_when: dnf_check_update.rc not in [0, 100]

# Repo may have an updated version.
# See also comment in main-tasks.yml
- name: Upgrade rpmfusion release package
  package:
    name: rpmfusion-{{ repo }}-release
    state: latest
