# Signing keys: https://rpmfusion.org/keys
#
# Notice RPMFusion supports secure upgrades between versions of Fedora.
# It will be possible to update this role's copy of the keys accordingly.
# Equally, if you already installed RPMFusion you could cross-check the keys.
#

- name: Create directories
  file:
    state: directory
    path: "/ansible-managed/rpmfusion/{{ item }}"
    mode: "755"
  with_items:
    - rpm-gpg
    - fingerprints

- name: Set filename for signing key
  set_fact:
    rpmfusion_key: "RPM-GPG-KEY-rpmfusion-{{ repo }}-fedora-{{ ansible_distribution_major_version }}"

- name: Copy signing keys
  copy:
    src: "{{ item }}/{{ rpmfusion_key }}"
    dest: "/ansible-managed/rpmfusion/{{ item }}/{{ rpmfusion_key }}"
  with_items:
    - rpm-gpg
    - fingerprints

# Ansible copy module does not preserve executable bit (unlike `cp`).
#
- name: Copy script for checking key fingerprints
  copy:
    src: "{{ item }}"
    dest: /ansible-managed/rpmfusion/
    mode: a+x
  with_items:
    - keyfile_to_fingerprints.sh

- name: Install gpg
  package: name=gpg state=present

# This role also includes fingerprints of the keys.
#
- name: Our key file matches our list of fingerprints
  shell: |
    VER={{ ansible_distribution_major_version|int }} &&
    KEY=RPM-GPG-KEY-rpmfusion-{{ repo }}-fedora-"$VER" &&
    ./keyfile_to_fingerprints.sh rpm-gpg/"$KEY" |
        diff -u fingerprints/"$KEY" /dev/stdin
  args:
    chdir: /ansible-managed/rpmfusion/
  changed_when: False
  check_mode: False

- name: Import signing key
  rpm_key:
    key: "/ansible-managed/rpmfusion/rpm-gpg/{{ rpmfusion_key }}"
    state: present
  register: import_key

# FIXME check mode above/below
  
# sourcejedi.rpmfusion_remove relies on descriptions to remove keys, because
# I don't know whether we're guaranteed to know all the installed RPM Fusion
# key IDs.  Check that this works for the key we just installed.
- name: Check description of installed signing key
  shell: |
    VER={{ ansible_distribution_major_version|int }} &&
    FPRINT="$(cat /ansible-managed/rpmfusion/fingerprints/RPM-GPG-KEY-rpmfusion-{{ repo }}-fedora-"$VER")" &&
    KEYID="$(echo "$FPRINT" | tr "A-F" "a-f" | tr -d ' \r\n' | tail --bytes 8 )" &&
    rpm -qa gpg-pubkey --qf "%{version}-%{release} %{summary}\n" | grep "RPM Fusion {{ repo }}.*\<.*\.rpmfusion\.org\>" | grep "$KEYID"
  check_mode: False
  changed_when: False
