# Ansible script to update the keys in this role from a managed node.
# About as horrifying as it sounds.

# Note fetch module does not support check mode.  That would be too easy.

- name: Update master keys
  fetch:
    src: '/etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-{{ repo }}-fedora-{{ ver }}'
    dest: '{{ role_path }}/files/rpm-gpg/'
    flat: yes
  with_items:
    - '{{ ansible_distribution_major_version|int }}'
    - '{{ ansible_distribution_major_version|int + 1 }}'
    - '{{ ansible_distribution_major_version|int + 2 }}'
  loop_control:
    loop_var: ver
  register:
    rpmfusion__master_keys_updated
  check_mode: no

- name: Check for unexpected changes in current master key
  assert:
    that: not rpmfusion__master_keys_updated.results[0].changed
    msg: >
      ERROR: UNEXPECTED CHANGE WHEN IMPORTING CURRENT GPG KEY FROM TARGET SYSTEM.
      PLEASE REVERT ALL CHANGED KEYS IMMEDIATELY.

- name: Update fingerprint of master key N+1
  shell: |
    VER={{ ansible_distribution_major_version|int + 1 }} &&
    ./keyfile_to_fingerprints.sh \
         rpm-gpg/RPM-GPG-KEY-rpmfusion-{{ repo }}-fedora-"$VER" \
         > fingerprints/RPM-GPG-KEY-rpmfusion-{{ repo }}-fedora-"$VER"
  args:
    chdir: "{{ role_path }}/files"
  delegate_to: 127.0.0.1
  when: rpmfusion__master_keys_updated.results[1].changed
  register: rpmfusion__fingerprint_1_update
  failed_when: rpmfusion__fingerprint_1_update.rc != 0 or rpmfusion__fingerprint_1_update.stderr_lines|length > 1

- name: Update fingerprint of master key N+2
  shell: |
    VER={{ ansible_distribution_major_version|int + 2 }} &&
    ./keyfile_to_fingerprints.sh \
         rpm-gpg/RPM-GPG-KEY-rpmfusion-{{ repo }}-fedora-"$VER" \
         > fingerprints/RPM-GPG-KEY-rpmfusion-{{ repo }}-fedora-"$VER"
  args:
    chdir: "{{ role_path }}/files"
  delegate_to: 127.0.0.1
  when: rpmfusion__master_keys_updated.results[2].changed
  register: rpmfusion__fingerprint_2_update
  failed_when: rpmfusion__fingerprint_2_update.rc != 0 or rpmfusion__fingerprint_2_update.stderr_lines|length > 1
  
- name: Check for update to future master keys
  assert:
    that: (not rpmfusion__master_keys_updated.results[1].changed) and
          (not rpmfusion__master_keys_updated.results[2].changed)
    msg: >
      WARNING: Imported new (or modified!) gpg keys from target system.
      Please double-check target system is trusted before continuing.
    # On subsequent retries we'll already have the new key,
    # so there won't be an error.
