galaxy_info:
  role_name: rpmfusion_free
  author: Alan Jenkins
  description: Enable the RPM Fusion "free" software repository, on Fedora Linux
  galaxy_tags:
    - repository
  license: GPLv3

  # rpmfusion__impl uses import_tasks / include_tasks
  min_ansible_version: 2.4

  platforms:
    - name: Fedora
      versions:
       - 35
       - 36


dependencies:
 - { role: sourcejedi.rpmfusion__impl, repo: free }
