---
- hosts: localhost
  roles:
    #- role: sestrella.ansible_role_asdf
    #  tags: 
    #    - network_access
    - role: jaredhocutt.gnome_extensions
      tags:
        - network_access
    - role: sourcejedi.rpmfusion_free
      become: true
    - role: geerlingguy.docker
      become: true
      tags:
        - network_access
    - commons
    - gnome
    # - jaredhocutt.gnome_extensions
