---
- hosts: localhost

  pre_tasks:
    - name: Include commons vars
      include_vars:
        file: 'commons_variables.yml'

  roles:
    # Basic one, to enable asdf
    - asdf
    # Full one, with ability to pre-install tools. Debian only
    #- role: sestrella.ansible_role_asdf
    #  tags:
    #    - network_access
    - role: jaredhocutt.gnome_extensions
      tags:
        - network_access
    - role: sourcejedi.rpmfusion_free
      become: true
      tags:
        - network_access
    #- role: geerlingguy.docker
    #  become: true
    #  tags:
    #    - network_access
    - commons
    - fedora
