---
- hosts: localhost

  pre_tasks:
    - name: Include commons vars
      include_vars:
        file: 'commons_variables.yml'
    - name: Update hostname
      hostname:
        name: '{{ host_hostname }}'
      when: host_hostname is defined

  roles:
    - role: jaredhocutt.gnome_extensions
      tags:
        - network_access
    - role: sourcejedi.rpmfusion_free
      become: true
      tags:
        - network_access
    # With fedora > 31, install docker manually
    #- role: geerlingguy.docker
    #  become: true
    #  tags:
    #    - network_access
    - commons
    # Basic one, to enable asdf
    - asdf
    - symlinks
    - fedora
