---
- hosts: localhost
  roles:
    - role: moviedo.nvm
      tags:
        - network_access
    - role: geerlingguy.docker
      become: true
      tags:
        - network_access
    - commons
    - gnome
    # - jaredhocutt.gnome_extensions
