---
- hosts: localhost
  vars_prompt:
    - name: git_email
      prompt: "What is your git email config ?"
      private: no
      default: "{{ default_git_email }}"

  roles:
    - role: geerlingguy.docker
      become: true
    # TODO Specify variables
    - commons
