---
- hosts: raspberry

  vars:
    docker_version: 5:20.10.5~3-0~raspbian-buster
    hostname: raspberry
    certbot_auto_renew: true
    certbot_auto_renew_user: "root"
    certbot_auto_renew_hour: "3"
    certbot_auto_renew_minute: "30"
    certbot_auto_renew_options: "--quiet --no-self-upgrade --renew-hook 'service nginx reload'"
    certbot_create_if_missing: true
    certbot_create_method: standalone
    certbot_admin_email: "{{ certbot_email }}"
    certbot_certs: []
    certbot_create_standalone_stop_services:
      - nginx

    pip_package: python3-pip
    docker_install_compose: true
    docker_users:
      - "{{ ansible_user_id }}"
  pre_tasks:
    - name: Include commons vars
      include_vars:
        file: "commons_variables.yml"
    - name: Update hostname
      become: true
      hostname:
        name: "{{ hostname }}"
    - name: Update hosts file
      become: true
      lineinfile:
        dest: /etc/hosts
        line: "127.0.0.1 {{ hostname }}"
        insertafter: "^127.0.0.1 localhost.*$"

  roles:
    - commons
    - role: geerlingguy.pip
      become: true
    - role: geerlingguy.docker_arm
      become: true
    - role: geerlingguy.mysql
      become: true
    # Required before asdf and symlinks
    - raspberry
    - asdf
    - symlinks
    - borgmatic
    - raspberry_app_media_center
    - raspberry_app_nas
    - raspberry_app_dyndns
    - role: geerlingguy.certbot
      become: true
