---
collections:
  - name: ansible.posix
  - name: community.general
  - name: donhector.workstation
    version: 1.1.0
roles:
  # TODO See https://github.com/PeterMosmans/ansible-role-customize-gnome as this one is archived ?
  - src: jaredhocutt.gnome_extensions
    version: master
  - src: sourcejedi.rpmfusion_free
    version: master
  - src: geerlingguy.pip
    version: 2.2.0
  - src: petermosmans.customize-gnome
    version: 0.2.10
  - src: geerlingguy.docker
    version: 6.0.4
