---
collections:
  - name: ansible.posix
    version: 1.5.4
  - name: community.general
    version: 8.6.5
  - name: donhector.workstation
    version: 1.1.0
roles:
  # TODO See https://github.com/PeterMosmans/ansible-role-customize-gnome as this one is archived ?
  - src: jaredhocutt.gnome_extensions
    version: master
  - src: sourcejedi.rpmfusion_free
    version: master
  - src: petermosmans.customize-gnome
    version: 0.2.12
  - src: geerlingguy.docker
    version: 7.0.2
