---
collections:
  - name: ansible.posix
  - name: community.general
  - name: donhector.workstation
    version: 1.1.0
roles:
  - src: jaredhocutt.gnome_extensions
    version: master
  - src: sourcejedi.rpmfusion_free
    version: master
  - src: geerlingguy.docker_arm
    version: 5.0.0
  - src: geerlingguy.pip
    version: 2.1.0
  - src: geerlingguy.mysql
    version: 3.5.0
  - src: geerlingguy.certbot
    version: 5.0.1
  - src: petermosmans.customize-gnome
    version: 0.2.5
  - src: geerlingguy.docker
    version: 4.2.4
