---
- hosts: dell
  roles:
    - role: geerlingguy.docker
      become: true
      tags: docker
    - role: fedora_dependencies
      become: true
      tags: fedora_dependencies
    - role: hostname
      become: true
      tags: hostname
    - role: jaredhocutt.gnome_extensions
      tags: gnome_extensions
    - role: ssh_config
      tags: ssh_config
    - role: git_config
      tags: git_config
    - role: kdrive
      tags: kdrive
    - role: ledger
      tags: ledger
    # - role: gnome
    #  tags: gnome
    - role: commons
      tags: commons
    - role: git_credential_keepassxc
      tags: git_credential_keepassxc
