---
- name: Ensure softs directory exists
  file:
    path: "~/.softs/"
    state: directory
    mode: "0755"

- name: "Download Jetbrains toolbox"
  unarchive:
    mode: 0700
    src: "https://download.jetbrains.com/toolbox/jetbrains-toolbox-{{ jetbrains_toolbox_version }}.tar.gz"
    dest: ~/.softs/
    remote_src: yes
    extra_opts:
      - "--strip-components=1"
  tags:
    - network_access

- name: Create desktop icon
  template:
    src: ./templates/toolbox.desktop.j2
    dest: ~/.local/share/applications/jetbrains-toolbox.desktop
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: "0644"
