---
- name: "Import Repositories GPG keys"
  become: true
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc
  tags:
    - network_access

- name: install VS Code repo (dnf)
  become: true
  yum_repository:
    name: code
    description: Visual Studio Code repo
    file: vscode
    baseurl: "https://packages.microsoft.com/yumrepos/vscode"
    gpgkey: "https://packages.microsoft.com/keys/microsoft.asc"
    gpgcheck: true

- name: "Install basic packages"
  become: true
  ansible.builtin.package:
    name:
      # VSCode Extensions
      # https://github.com/gantsign/ansible-role-visual-studio-code
      - libappindicator
      - dconf-editor
      - NetworkManager-tui
      - firefox
      - gimp
      - gpaste-ui
      - gpaste
      - vlc
      - xclip
      - fortune-mod
      - code
      - qrencode
      - keepassxc
      - seahorse
      - chromium
      # Gnome related
      - python3-devel
      - flatpak
      - gnome-tweaks
      - guake
      - thunderbird
      - filezilla
    state: latest
  tags:
    - network_access

- name: "Remove unwanted packages"
  become: true
  ansible.builtin.package:
    name:
      - gnome-maps
      - gnome-documents
      - rhythmbox
    state: absent
  tags:
    - network_access

- name: Ensure dependencies are locally met to manage dconf
  pip:
    name: psutil>4.0
    extra_args: --user
  tags:
    - network_access
  when: user_pip is not defined

# FIXME temporary condition until asdf pip is removed
- name: Ensure dependencies are locally met to manage dconf
  pip:
    name: psutil>4.0
  tags:
    - network_access
  when: user_pip is defined
