---
- name: Clone asdf repository
  git:
    repo: git@github.com:asdf-vm/asdf.git
    dest: "~/.asdf"
    version: v0.10.1

- name: Enable asdf
  blockinfile:
    path: ~/.bashrc
    insertbefore: BOF
    marker: "#{mark} ANSIBLE ASDF MANAGED BLOCK"
    block: |
      . $HOME/.asdf/asdf.sh
      . $HOME/.asdf/completions/asdf.bash
