---
- name: Add the flathub flatpak repository remote to the user installation
  become: true
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install flatpak app
  flatpak:
    name: "{{ item }}"
    state: present
  loop: "{{ fedora_dependencies_flatpak }}"
