---
- name: Add the flathub flatpak repository remote to the user installation
  become: true
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
  tags:
    - network_access

- name: Install the spotify flatpak
  flatpak:
    name: https://flathub.org/repo/appstream/com.spotify.Client.flatpakref
    state: present
  tags:
    - network_access

- name: Install the Postman flatpak
  flatpak:
    name: https://flathub.org/repo/appstream/com.getpostman.Postman.flatpakref
    state: present
  tags:
    - network_access

- name: Install the OnlyOffice flatpak
  flatpak:
    name: https://flathub.org/repo/appstream/org.onlyoffice.desktopeditors.flatpakref
    state: present
  tags:
    - network_access

- name: Install the Discord flatpak
  flatpak:
    name: https://flathub.org/repo/appstream/com.discordapp.Discord.flatpakref
    state: present
  tags:
    - network_access

- name: Install the Signal flatpak
  flatpak:
    name: https://flathub.org/repo/appstream/org.signal.Signal.flatpakref
    state: present
  tags:
    - network_access

- name: Install the Gnome extensions (fedora >= 34 only)
  flatpak:
    name: https://flathub.org/repo/appstream/org.gnome.Extensions.flatpakref
    state: present
  tags:
    - network_access
  when: ansible_distribution  == "Fedora" and ansible_distribution_major_version | int >= 34
