---

- import_tasks: packages.yml

- import_tasks: kDrive.yml

- import_tasks: ledger.yml
  when: install_ledger is defined and install_ledger

- import_tasks: jetbrains.yml

- import_tasks: flatpak.yml

- import_tasks: dconf.yml

- name: Set SELinux in permissive mode
  become: true
  ansible.posix.selinux:
    policy: targeted
    state: permissive
