---
- name: Ensure CRM app folder exists
  file:
    mode: "0700"
    path: "{{ crm_app.base_path }}"
    state: directory

- name: Copy docker-compose configuration
  copy:
    src: "{{ role_path }}/files/docker-compose.yml"
    dest: "{{ crm_app.base_path }}/"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: "0644"

- name: Template environment file
  template:
    src: templates/.env.j2
    dest: "{{ crm_app.base_path }}/.env"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: "0644"

- name: Template nginx host
  become: true
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/sites-available/001-crm.conf
    owner: "root"
    group: "root"
    mode: "0644"

- name: Enable nginx host
  become: true
  ansible.builtin.file:
    src: /etc/nginx/sites-available/001-crm.conf
    dest: /etc/nginx/sites-enabled/001-crm.conf
    owner: root
    group: root
    state: link

- name: Add domain to certificate to be generated
  set_fact:
    certbot_certs: '{{ certbot_certs + [ { "domains": [crm_app.domain] } ] }}'

- name: Template CRM backup configuration
  become: true
  template:
    src: templates/crm.yaml.j2
    dest: /etc/borgmatic.d/crm.yaml
    owner: root
    group: root
    mode: "0600"
    validate: /root/.local/bin/validate-borgmatic-config -c %s

- name: Copy CRM cron service
  become: true
  template:
    src: "templates/crm-cron.service.j2"
    dest: "/etc/systemd/system/crm-cron.service"
    owner: "root"
    group: "root"
    mode: "0600"

- name: Copy CRM cron timer
  become: true
  template:
    src: "templates/crm-cron.timer.j2"
    dest: "/etc/systemd/system/crm-cron.timer"
    owner: "root"
    group: "root"
    mode: "0600"

#! - name: Enable CRM docker service
#!   become: true
#!   systemd:
#!     state: started
#!     enabled: false
#!     name: dc@crm.service

- name: Enable CRM timer
  become: true
  systemd:
    state: started
    enabled: true
    name: crm-cron.timer
