---
betisier_app:
  base_path: /apps/betisier
  user: betisier
  db: betisier
  password: redacted
  domain: redacted
  salt: redacted
  borg_repository: betisier

healthchecks_urls:
  betisier: redacted
