---
- name: "Clone repository to configure domain {{ item.domain }}"
  git:
    repo: git@github.com:cavebeat/gandi-live-dns.git
    dest: "{{ dyndns_app.base_path }}/{{ item.domain }}"
    version: master
- name: "Generate configuration file for {{ item.domain }} from template"
  template:
    src: "templates/{{ item.config }}.j2"
    dest: "{{ dyndns_app.base_path }}/{{ item.domain }}/src/config.py"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: "0644"

- name: "Template {{ item.domain }} service"
  become: true
  template:
    src: "templates/dyndns.service.j2"
    dest: "/etc/systemd/system/dyndns.{{ item.domain }}.service"
    owner: "root"
    group: "root"
    mode: "0600"

- name: "Copy {{ item.domain }} timer"
  become: true
  template:
    src: "templates/dyndns.timer.j2"
    dest: "/etc/systemd/system/dyndns.{{ item.domain }}.timer"
    owner: "root"
    group: "root"
    mode: "0600"

- name: "Enable {{ item.domain }} service"
  become: true
  systemd:
    enabled: true
    name: "dyndns.{{ item.domain }}.service"

- name: "Enable dyndns.{{ item.domain }} timer"
  become: true
  systemd:
    state: started
    enabled: true
    name: "dyndns.{{ item.domain }}.timer"
