---
- name: "Install basic packages"
  become: true
  ansible.builtin.package:
    name:
      - ansible
      - git
      - git-lfs
      - make
      - unzip
      - htop
      - wget
      - curl
      - tmux
      - vim
      - rsync
      - jq
      - gnupg2
    state: latest
  tags:
    - network_access
