---
- name: Upgrade all packages except kernel
  become: yes
  dnf:
    name: "*"
    state: latest
    exclude:
      - "kernel*"
  tags:
    - network_access

- name: "Import Repositories GPG keys"
  become: yes
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc
  tags:
    - network_access

- name: "Install basic packages"
  become: yes
  dnf:
    name:
      - ansible
      - git
      - make
      - unzip
      - htop
      - wget
      - curl
      - tmux
      - xclip
      - vim
      - firefox
      - rsync
      - gimp
      - vlc
      - fortune-mod
      - cowsay
      - code
      - gnupg2
      - qrencode
      - nextcloud-client
      - keepassxc
      - seahorse
      - chromium
      - "https://downloads.slack-edge.com/linux_releases/slack-4.3.2-0.1.fc21.x86_64.rpm"
    # Extensions
    # https://github.com/gantsign/ansible-role-visual-studio-code
    state: latest
  tags:
    - network_access
