---
- name: Ensure SSH custom settings folder exists
  file:
    path: ~/.ssh_config
    state: directory
    mode: "0755"

- name: Copy base host
  copy:
    src: ./templates/base_hosts
    dest: ~/.ssh_config/base_hosts
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: "0644"

- name: Create a SSH key
  openssh_keypair:
    path: ~/.ssh/id_user_ed25519
    state: present
    type: ed25519
    force: no
    comment: "{{ ansible_env['USERNAME'] }}@{{ ansible_hostname }}"
  register: ssh_key_status

- name: "Log new public key for reference"
  when: ssh_key_status.changed
  debug:
    msg: "{{ ssh_key_status.public_key }}"

- name: Create a SSH key for git
  openssh_keypair:
    path: ~/.ssh/id_git_ed25519
    state: present
    type: ed25519
    force: no
    comment: "{{ ansible_env['USERNAME'] }}@{{ ansible_hostname }} - git"
  register: ssh_key_status_git

- name: "Log new public key for reference"
  when: ssh_key_status_git.changed
  debug:
    msg: "{{ ssh_key_status_git.public_key }}"
