--- 
- name: Ensure SSH folder exists
  file:
    path: ~/.ssh
    state: directory
    mode: "0700"

- name: Ensure SSH config exists
  file:
    path: ~/.ssh/config
    state: file
    mode: "0600"

- name: Create a SSH key
  openssh_keypair:
    path: ~/.ssh/id_ed25519
    state: present
    type: ed25519
    force: no
    comment: "{{ ansible_env['USERNAME'] }}@{{ ansible_hostname }}"
  register: ssh_key_status
  notify:
    - print ssh key
    - upload ssh key github
  
- name: Render base host template
  set_fact:
    hosts_content: "{{ lookup('template', './templates/common_hosts') }}"

- name: Render base host template
  set_fact:
    ssh_base_config: "{{ lookup('template', './templates/ssh_config') }}"

- name: Template SSH base hosts
  blockinfile:
    dest: "~/.ssh/config"
    content: '{{ hosts_content }}'
    state: present

- name: Template SSH base config
  blockinfile:
    dest: "~/.ssh/config"
    content: '{{ ssh_base_config }}'
    state: present
