---
- name: Ensure SSH folder exists
  file:
    path: ~/.ssh
    state: directory
    mode: "0700"

- name: Ensure SSH config exists
  copy:
    content: ""
    dest: "~/.ssh/config"
    force: false
    group: "{{ ansible_user_gid }}"
    owner: "{{ ansible_user_uid }}"
    mode: 0600

- name: Create a SSH key
  openssh_keypair:
    path: ~/.ssh/id_ed25519
    state: present
    type: ed25519
    force: false
    comment: "{{ ansible_user_id }}@{{ ansible_hostname }}"
  register: ssh_key_status
  notify:
    - print ssh key
    - upload ssh key github

- name: Render base host template
  set_fact:
    ssh_base_config: "{{ lookup('template', 'ssh_config.j2') }}"

- name: Template SSH Config
  blockinfile:
    dest: "~/.ssh/config"
    block: |
      {{ item.content }}
    marker: "#{mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
  loop:
    - name: base
      content: "{{ ssh_base_config }}"

- name: Trigger handler
  meta: flush_handlers
