---
- name: Setup dotfiles symlinks
  include_tasks: symlink.yml
  loop:
    - .vimrc
    - .bash_profile
    - .bash_aliases
    - .gitconfig
    - .tmux.conf
    - .config/starship.toml
    - .gnupg/gpg.conf
    - .default-npm-packages
    - .asdfrc
