---
- name: "{{ role_name }} : Set the hostname"
  hostname:
    name: "{{ hostname_name }}"
  when: hostname_name is defined

- name: "{{ role_name }} : Update the hostname - (/etc/hosts)"
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ ansible_default_ipv4.address }}"
    line: "{{ ansible_default_ipv4.address }}    {{ hostname_fqdn }}    {{ hostname_name }}"
    state: present
  when: hostname_name is defined and hostname_fqdn is defined

- name: "{{ role_name }} : Update the hostname - (/etc/hosts)"
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.0.1 {{ hostname_name }}"
    line: "127.0.0.1 {{ hostname_name }}"
    state: present
  when: hostname_name is defined and hostname_fqdn is defined
