---
- name: "{{ role_name }} : Set the hostname"
  hostname:
    name: "{{ hostname.name }}"
  when: hostname.name is defined

- name: "{{ role_name }} : Update the hostname - (/etc/hosts)"
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ ansible_default_ipv4.address }}"
    line: "{{ ansible_default_ipv4.address }}    {{ hostname.fqdn }}    {{ hostname.name }}"
    state: present
  when: hostname.name is defined and hostname.fqdn is defined

- name: "{{ role_name }} : Update the hostname - (/etc/hosts)"
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.0.1 {{ hostname.name }}"
    line: "127.0.0.1 {{ hostname.name }}"
    state: present
  when: hostname.name is defined and hostname.fqdn is defined
