---
- name: Clone asdf repository
  git:
    repo: git@github.com:asdf-vm/asdf.git
    dest: '~/.asdf'
    version: v0.8.0

- name: Enable asdf
  blockinfile:
    path: ~/.bashrc
    insertbefore: BOF
    marker: '#{mark} ANSIBLE ASDF MANAGED BLOCK'
    block: |
      . $HOME/.asdf/asdf.sh
      . $HOME/.asdf/completions/asdf.bash

- name: Get info on asdfrc file
  stat:
    path: '~/.asdfrc'
  register: asdfrc

- name: Delete asdfrc if not a symlink
  file:
    path: '~/.asdfrc'
    state: absent
  when: asdfrc.stat is defined and asdfrc.stat.islnk is defined and not asdfrc.stat.islnk

- name: Create symlink
  file:
    src: ~/dotfiles/home/.asdfrc
    dest: '~/.asdfrc'
    state: link
    force: no
