---
- name: Render custom scripts Template
  set_fact:
    custom_script_template: "{{ lookup('template', 'custom_scripts.sh.j2') }}"

- name: Add custom script in bashrc
  blockinfile:
    insertafter: '#!/usr/bin/env bash'
    dest: "~/.bashrc"
    block: |
      # See donhector.workstation.asdf role
      source ~/.shellrc.d/asdf.sh

      if [ -d ~/dotfiles/ansible/bashrc.d ]; then
        for file in ~/dotfiles/ansible/bashrc.d/*.sh
        do
          source $file
        done
      fi

      if [ -d ~/.bashrc.d ]; then
        for file in ~/.bashrc.d/*
        do
          source $file
        done
      fi

      if [ -f ~/.bash_aliases ]; then
        source ~/.bash_aliases
      fi
    marker: "#{mark} ANSIBLE STARTUP SCRIPTS"

- name: Add custom script in bashrc
  blockinfile:
    insertafter: 'EOF'
    dest: "~/.bashrc"
    block: |
      {{ custom_script_template }}
    marker: "#{mark} ANSIBLE CUSTOM SCRIPTS"
