---
- include: packages.yml

# See ansible/home/.gitconfig where this file is included
- name: Template git config
  template:
    src: templates/git_user.j2
    dest: ~/.git_user
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: "0644"

- name: Ensure local bin directory exists
  file:
    path: "~/.local/bin"
    state: directory
    mode: "0755"

- name: Set timezone to Europe/Paris
  become: true
  timezone:
    name: Europe/Paris

- name: Ensure that .bashrc load custom scripts
  blockinfile:
    path: ~/.bashrc
    block: |
      # User specific environment
      if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
      then
          PATH="$HOME/.local/bin:$HOME/bin:$PATH"
          export PATH
      fi
      if [ -d ~/dotfiles/ansible/bashrc.d ]; then
        for file in ~/dotfiles/ansible/bashrc.d/*.sh
        do
            source $file
        done
      fi
      if [ -f ~/.bash_aliases ]; then
        source ~/.bash_aliases
      fi
      [[ $- == *i* ]] && command -v starship >/dev/null && eval "$(starship init bash)"
      [[ $- == *i* ]] && command -v npm >/dev/null && source <(npm completion)
      [[ $- == *i* ]] && command -v kubectl >/dev/null && source <(kubectl completion bash)
