---
- name: Ensure local bin directory exists
  file:
    path: "~/.local/bin"
    state: directory
    mode: "0755"

- name: Set timezone to Europe/Paris
  become: true
  timezone:
    name: Europe/Paris

- import_tasks: add_to_path.yaml
- import_tasks: custom_scripts.yaml

- name: Setup symlinks
  include_tasks: symlink.yml
  loop: "{{ commons_symlinks }}"
