---
- hosts: localhost

  pre_tasks:
    - name: Include desktop vars
      include_vars:
        file: "../desktop_vars.yml"
    - name: Include secrets vars
      include_vars:
        file: "../../variables.yml"
    - name: "Include locals vars for {{ ansible_play_name }} playbook"
      include_vars:
        file: "locals.yml"

  roles:
    - role: hostname
      become: true
    - role: jaredhocutt.gnome_extensions
      tags:
        - network_access
    - role: sourcejedi.rpmfusion_free
      become: true
      tags:
        - network_access
    - commons
    # Basic one, to enable asdf
    - asdf
    - symlinks
    - fedora
