galaxy_info:
  role_name: gnome_extensions

  author: Jared Hocutt (@jaredhocutt)
  description: >-
    This role handles installing the specified Gnome Shell extensions.

  license: MIT

  # Reason: loop
  min_ansible_version: 2.5

  platforms:
  - name: Fedora
    versions:
    - all

  galaxy_tags:
    - gnome
    - gnome-shell
    - extensions
    - system

dependencies: []
