---
# Hostname role
hostname:
  name: gibbs
  fqdn: gibbs.sylvain.dev

# Commons role
custom_packages:
    - apt-transport-https
    - nginx
    - cron
    - sendemail
    - mailutils

# Docker settings
docker_compose_version: "1.29.1"
docker_install_compose: true
docker_users:
  - "{{ ansible_user_id }}"

# MySQL settings
mysql_root_password: "{{ gibbs.mysql_root_password }}"
mysql_databases:
  - name: "{{ crm_app.db }}"
    encoding: utf8mb4
    collation: utf8mb4_general_ci
  - name: "{{ rss_app.db }}"
    encoding: utf8mb4
    collation: utf8mb4_general_ci
  - name: "{{ nextcloud_app.db }}"
    encoding: utf8mb4
    collation: utf8mb4_general_ci
mysql_users:
  - name: "{{ crm_app.user }}"
    host: "%"
    password: "{{ crm_app.password }}"
    priv: "{{ crm_app.user }}.*:ALL"
  - name: "{{ rss_app.user }}"
    host: "%"
    password: "{{ rss_app.password }}"
    priv: "{{ rss_app.user }}.*:ALL"
  - name: "{{ nextcloud_app.user }}"
    host: "%"
    password: "{{ nextcloud_app.password }}"
    priv: "{{ nextcloud_app.user }}.*:ALL"

# Certbot settings
certbot_auto_renew: true
certbot_auto_renew_user: "root"
certbot_auto_renew_hour: "4"
certbot_auto_renew_minute: "30"
certbot_auto_renew_options: "--quiet --no-self-upgrade --renew-hook 'service nginx reload'"
certbot_create_if_missing: true
certbot_create_method: standalone
certbot_admin_email: "{{ certbot_email }}"

# Will be dynamically defined be apps roles
certbot_certs: []

certbot_create_standalone_stop_services:
  - nginx
