---
- name: Install Gnome required package
  become: yes
  dnf:
    name:
      - python3-devel
      - flatpak
      - gnome-tweaks
      - guake
      - thunderbird
      - filezilla
    state: latest
  tags:
    - network_access

- name: Ensure dependencies are locally met to manage dconf
  pip:
    name: psutil>4.0
    extra_args: --user
  tags:
    - network_access

- include: flatpak.yml

- include: dconf.yml

# - include_role:
#     name: jaredhocutt.gnome_extensions
