---
- name: Display battery percentage
  dconf:
    key: "/org/gnome/desktop/interface/show-battery-percentage"
    value: "true"
    state: present

- name: Configure buttons layout
  dconf:
    key: "/org/gnome/desktop/wm.preferences/button-layout"
    value: "'appmenu:minimize,maximize,close'"
    state: present

- name: Limit switch applications to current workspace only
  dconf:
    key: "/org/gnome/shell/app-switcher/current-workspace-only"
    value: "true"
    state: present

- name: Disallow location access
  dconf:
    key: "/org/gnome/system/location/enabled"
    value: "false"
    state: present

# See https://askubuntu.com/a/1071888
- name: Allow separate multiple windows per workspace
  dconf:
    key: "/org/gnome/mutter/workspaces-only-on-primary"
    value: "false"
    state: present

# See https://superuser.com/a/860001
- name: Disable switch applications
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-applications"
    value: "@as []"
    state: present
- name: Enable switch windows instead of applications
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-windows"
    value: "['<Super>Tab', '<Alt>Tab']"
    state: present
- name: Disable switch applications backward
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-applications-backward"
    value: "@as []"
    state: present
- name: Enable switch windows backward instead of applications
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-windows-backward"
    value: "['<Shift><Super>Tab', '<Shift><Alt>Tab']"
    state: present

- name: Clipboard extension - disable shortcut
  dconf:
    key: "/org/gnome/shell/extensions/clipboard-indicator/enable-keybindings"
    value: "false"
    state: present

- name: Setup GPG Keyservers
  dconf:
    key: "/desktop/gnome/crypto/pgp/keyservers"
    value: "['hkp://pool.sks-keyservers.net', 'ldap://keyserver.pgp.com']"
    state: present

- name: Configure guake
  block:
    - name: Set bind key
      dconf:
        key: "/apps/guake/keybindings/global/show-hide"
        value: "'twosuperior'"
        state: present
    - name: Set transparency
      dconf:
        key: "/apps/guake/style/background/transparency"
        value: "86"
        state: present
    - name: Enable dark theme
      dconf:
        key: "/apps/guake/general/gtk-prefer-dark-theme"
        value: "true"
        state: present
    - name: Enable infinite history
      dconf:
        key: "/apps/guake/general/infinite-history"
        value: "true"
        state: present
    - name: Disable popup when start
      dconf:
        key: "/apps/guake/general/use-popup"
        value: "false"
        state: present
    - name: Set height
      dconf:
        key: "/apps/guake/general/window-height"
        value: "71"
        state: present
    - name: Set start after login
      dconf:
        key: "/apps/guake/general/start-at-login"
        value: "true"
        state: present
    - name: Save when changed
      dconf:
        key: "/apps/guake/general/save-tabs-when-changed"
        value: "true"
        state: present
    - name: Gnome shortcut name
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name"
        value: "'Guake Toggle'"
        state: present
    - name: Gnome shortcut command
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command"
        value: "'/usr/bin/guake-toggle'"
        state: present
    - name: Gnome shortcut key
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding"
        value: "'twosuperior'"
        state: present
    # @see https://gist.github.com/carlwgeorge/c560a532b6929f49d9c0df52f75a68ae#file-gnome-yml-L85
    - name: enable custom keybindings
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
        value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"
