---
# Job template - to be used in a pipeline by including this file.
# Make sure to include the .sast stage in the pipeline template
#
# Lints an Ansible playbook
#
# include:
#  - .gitlab/ansible-lint.gitlab-ci.yml

ansible-lint:
  extends: .sast
  dependencies: []
  image:
    name: gofwd/tools-image
    entrypoint: [""]
  script:
    - ansible-lint .
