---
- name: Ensure ledger folder exists
  become: true
  file:
    path: "{{ ledger_folder }}"
    state: directory
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: "0755"

- name: "Download ledger"
  get_url:
    url: "{{ ledger_url }}"
    dest: "{{ ledger_folder }}/ledger"
    mode: "0700"

- name: Create desktop icon
  template:
    src: ./templates/ledger.desktop.j2
    dest: ~/.local/share/applications/ledger.desktop
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: "0644"
