---
- name: Get Gnome Shell extension info for {{ item.id }}
  ansible.builtin.uri:
    url: https://extensions.gnome.org/extension-info/?pk={{ item.id }}&shell_version={{ gnome_shell_version }}
    return_content: true
  register: r_gnome_extension_info
  when: "'name' not in item or 'url' not in item"

- name: Add gnome_extension item with additional info to gnome_extensions_full
  ansible.builtin.set_fact:
    gnome_extensions_full: |
      {{ gnome_extensions_full | default([]) + [ {
        'id': item.id,
        'name': item.name | default( r_gnome_extension_info.json.uuid ),
        'url': item.url | default( 'https://extensions.gnome.org' + r_gnome_extension_info.json.download_url ),
        'enable': item.enable | default( false )
      } ] }}
  when: "'skipped' not in r_gnome_extension_info"

- name: Add original gnome_extensions item to gnome_extensions_full
  ansible.builtin.set_fact:
    gnome_extensions_full: "{{ gnome_extensions_full | default([]) + [ item ] }}"
  when: "'skipped' in r_gnome_extension_info"
