---
language: python
python: "2.7"
sudo: true

env:
  - SITE=test.yml

before_install:
  - sudo apt-get update -qq 1>/dev/null

install:
  # Install Ansible.
  - pip install ansible 1>/dev/null

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  # Check the role/playbook's syntax.
  - "ansible-playbook -i tests/inventory tests/$SITE --syntax-check"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
