---
# ASDF
asdf_plugins:
  - name: "rust"
    repository: "https://github.com/asdf-community/asdf-rust.git"
    versions:
      - "1.75.0"
    global: "1.75.0"
    yum_deps: []
  - name: "terraform"
    versions:
      - "1.2.5"
    global: "1.2.5"
    yum_deps: []
  - name: "direnv"
    versions: ["latest"]
    global: "latest"
    yum_deps: []
  - name: "fzf"
    versions: ["latest"]
    global: "latest"
    yum_deps: []
  - name: "starship"
    versions: ["latest"]
    global: "latest"
    yum_deps: []
  - name: "age"
    repository: "https://github.com/threkk/asdf-age.git"
    yum_deps: []
    global: "latest"
    versions: ["latest"]

asdf_version: "v0.14.0"
asdf_legacy_version_file: "no"

# HOSTNAME
hostname_name: dell
hostname_fqdn: dell.localhost

# GNOMES EXTENSIONS
gnome_extension_ids:
  # https://extensions.gnome.org/extension/6242/emoji-copy/
  - 6242
  # https://extensions.gnome.org/extension/615/appindicator-support/
  - 615
  # https://extensions.gnome.org/extension/600/launch-new-instance/
  - 600
  # https://extensions.gnome.org/extension/1262/bing-wallpaper-changer/
  - 1262
  # https://extensions.gnome.org/extension/7/removable-drive-menu/
  - 7
  # https://extensions.gnome.org/extension/4679/burn-my-windows/
  - 4679

# DOCKER
docker_install_compose_plugin: false
docker_compose_package: docker-compose-plugin
docker_compose_package_state: present
docker_users: ["{{ ansible_user_id }}"]
