---
- name: Install docker
  become: true
  ansible.builtin.dnf:
    name: "moby-engine"
    state: present
    update_cache: true

- name: Ensure group "docker" exists
  become: true
  ansible.builtin.group:
    name: docker
    state: present

- name: Adding current user to docker group
  become: true
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true

- name: "Enable docker service"
  become: true
  systemd:
    enabled: true
    name: "docker.service"
