---

- name: Ensure data folder exists
  become: true
  file:
    path: "/data"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: Mount external hard drive
  become: true
  mount:
    path: /data
    src: "UUID={{ hard_drive_uuid }}"
    fstype: ext4
    opts: auto,nofail,noatime,rw,user
    state: present

- name: Set timezone to Europe/Paris
  become: true
  timezone:
    name: Europe/Paris

- name: Ensure unused service are disabled
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  with_items:
    - hciuart
    - avahi-daemon

- name: Clone dotfile repository
  git:
    repo: git@github.com:sylvainmetayer/dotfiles.git
    dest: "~/dotfiles"
    # FIXME use master when merged
    version: feat_raspberry

- name: Install commons packages
  become: true
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
    cache_valid_time: 86400
  loop:
    - git
    - x11-xkb-utils
    - apt-transport-https
    - nginx
    - unzip
    - curl
    - gnupg2
    - cron
    - sendemail
    - mailutils

- name: Configure SSH settings
  include_tasks: ssh.yml
  args:
    apply:
      become: true

- name: Configure fail2ban
  include_tasks: fail2ban.yml
  args:
    apply:
      become: true

- name: Copy docker-compose service
  become: true
  copy:
    src: "{{ role_path }}/files/dc@.service"
    dest: "/etc/systemd/system/dc@.service"
    owner: "root"
    group: "root"
    mode: "0600"

- name: Copy nginx configuration
  become: true
  copy:
    src: "{{ role_path }}/files/nginx.conf"
    dest: "/etc/nginx/nginx.conf"
    owner: "root"
    group: "root"
    mode: "0644"
