---
- name: Print Public SSH key
  debug:
    msg: "{\"title\": \"{{ ansible_hostname }} Key\", \"key\": \"{{ ssh_key_status.public_key }}\"}"
  listen: "print ssh key"

  # TODO Gitlab 
- name: Add SSH Key to Github
  uri:
    url: https://api.github.com/user/keys
    method: POST
    body: "{\"title\": \"{{ ansible_hostname }} Key\", \"key\": \"{{ ssh_key_status.public_key }}\"}"
    status_code: 201
    body_format: json
    headers:
      Accept: application/vnd.github.v3+json
      Authorization: "token {{ github_token }}"
  listen: "upload ssh key github"
  when: github_token is defined
