---
- name: restart docker
  ansible.builtin.service:
    name: docker
    state: "{{ docker_restart_handler_state }}"
  ignore_errors: "{{ ansible_check_mode }}"
  when: docker_service_manage | bool

- name: apt update
  ansible.builtin.apt:
    update_cache: true
