---
- name: Ensure required folder exists
  file:
    path: "{{ item }}"
    state: directory
    mode: "0700"
  with_items:
    - ~/.ssh
    - ~/.config/systemd/user/
    - ~/.config/autostart

- include_tasks: ssh_config.yaml
- include_tasks: disable_gnome_ssh_agent.yaml
- include_tasks: ssh_agent.yaml

- name: Copy keepassxc.pub to .ssh folder
  ansible.builtin.copy:
    src: ./files/keepassxc.pub
    dest: ~/.ssh/keepassxc.pub
    group: "{{ ansible_user_gid }}"
    owner: "{{ ansible_user_uid }}"
    mode: "0600"

# Improvment : we need to make sure the "Ask user confirmation before using key" is disabled

# sources
# https://keepassxc.org/docs/#faq-ssh-agent-auth-errors
# https://www.padok.fr/en/blog/ssh-keys-keepassxc
# https://peterbabic.dev/blog/make-ssh-prompt-password-keepassxc/
# https://wiki.gnome.org/Projects/GnomeKeyring/Ssh
