- name: "Link work related script"
  file:
    src: ~/dotfiles/ansible/roles/fedora_work/files/gop.sh
    dest: ~/.gop.sh
    state: link
    force: false

- name: Load work script
  blockinfile:
    path: ~/.bashrc
    insertbefore: EOF
    marker: "#{mark} ANSIBLE WORK MANAGED BLOCK"
    block: |
      . $HOME/.gop.sh

