---
joplin_url: "https://github.com/laurent22/joplin/releases/download/v2.12.19/Joplin-2.12.19.AppImage"
# https://github.com/laurent22/joplin/releases => yaml file and update sha512
joplin_sha512sum: "t7ADQDdlfKDHwhA7L4hJJdxm+m+lzD0XwpqVmips0BQLz8RHPh1XmzlY/7lUPRfVfwLIXriuc1FnDAvBvPhMJA=="
joplin_folder: "/opt/joplin"
