---
name: Ansible

on: [push]
# From https://dev.to/koh_sh/automatic-ansible-lint-with-github-actions-52oe
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9, '3.10']
        ansible-version: [6.1.0]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Ansible ${{ matrix.ansible-version }}
      run: |
        python -m pip install --upgrade pip
        pip install yamllint ansible==${{ matrix.ansible-version }}
    - name: Lint playbook
      run: |
        cp params/variables.yml.sample params/variables.yml
        ansible-galaxy role install -r ansible/requirements.yml
        ansible-galaxy collection install -r ansible/requirements.yml
        ansible-playbook ansible/playbooks/fedora/main.yml --syntax-check
        ansible-playbook ansible/playbooks/gibbs/main.yml --syntax-check
        ansible-playbook ansible/playbooks/fedora_work/main.yml --syntax-check
        yamllint ansible

